version: "3"
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME="root"
      - MONGO_INITDB_ROOT_PASSWORD="asdf1234"
    ports:
      - "27017:27017"

  app:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - DB_USERNAME="root"
      - DB_PASSWORD="asdf1234"
      - DB_HOST=mongodb
      - DB_PORT=27017
      - MAIL_USERNAME=""
      - MAIL_PASSWORD=""
    links:
      - mongodb
    depends_on:
      - mongodb
